// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfHttpEvent struct {
	_           structs.HostLayout
	Pid         uint32
	Sport       uint16
	Dport       uint16
	TimestampNs uint64
	DurationNs  uint64
	StatusCode  uint16
	Method      [8]uint8
	Path        [128]uint8
	Comm        [16]uint8
	_           [6]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceReadEnter *ebpf.ProgramSpec `ebpf:"trace_read_enter"`
	TraceReadExit  *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceWrite     *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveFds  *ebpf.MapSpec `ebpf:"active_fds"`
	HttpBuf    *ebpf.MapSpec `ebpf:"http_buf"`
	HttpEvents *ebpf.MapSpec `ebpf:"http_events"`
	StartTime  *ebpf.MapSpec `ebpf:"start_time"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveFds  *ebpf.Map `ebpf:"active_fds"`
	HttpBuf    *ebpf.Map `ebpf:"http_buf"`
	HttpEvents *ebpf.Map `ebpf:"http_events"`
	StartTime  *ebpf.Map `ebpf:"start_time"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveFds,
		m.HttpBuf,
		m.HttpEvents,
		m.StartTime,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceReadEnter *ebpf.Program `ebpf:"trace_read_enter"`
	TraceReadExit  *ebpf.Program `ebpf:"trace_read_exit"`
	TraceWrite     *ebpf.Program `ebpf:"trace_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceReadEnter,
		p.TraceReadExit,
		p.TraceWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
