//go:build ignore

// eBPF program for Kerno — traces HTTP traffic via write/read syscalls.
//
// Data flow:
//   sys_enter_write  →  detect HTTP request, store event + timestamp in maps
//   sys_enter_read   →  save fd so the exit handler can reconstruct the map key
//   sys_exit_read    →  compute latency, emit completed HttpEvent to ring buffer

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

// These structs are generated by the kernel from tracepoint definitions and
// are not present in any standard header — they must be defined manually.
struct trace_event_raw_sys_enter {
    __u16 common_type;
    __u8  common_flags;
    __u8  common_preempt_count;
    __s32 common_pid;
    long  id;
    long  args[6]; // syscall arguments: args[0]=fd, args[1]=buf, args[2]=count, ...
};

struct trace_event_raw_sys_exit {
    __u16 common_type;
    __u8  common_flags;
    __u8  common_preempt_count;
    __s32 common_pid;
    long  id;
    long  ret; // return value of the syscall
};

// HttpEvent carries one completed HTTP request/response pair to user space.
// Must match the Go struct HttpEvent in internal/collector/types.go exactly.
struct http_event {
    __u32 pid;
    __u16 sport;
    __u16 dport;
    __u64 timestamp_ns;
    __u64 duration_ns;
    __u16 status_code;
    __u8  method[8];
    __u8  path[128];
    __u8  comm[16];
};

// ── Maps ─────────────────────────────────────────────────────────────────────

// http_events — ring buffer that delivers completed events to user space.
struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} http_events SEC(".maps");

// start_time — records when each (pid, fd) pair sent its HTTP request.
// Key: (pid << 32) | fd
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, __u64);
    __uint(max_entries, 10240);
} start_time SEC(".maps");

// http_buf — holds the partially-filled http_event while we wait for the response.
// Key: (pid << 32) | fd
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u64);
    __type(value, struct http_event);
    __uint(max_entries, 10240);
} http_buf SEC(".maps");

// active_fds — saves the fd used in sys_enter_read so sys_exit_read can
// reconstruct the (pid, fd) key without re-reading it from arguments.
// Key: pid
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __type(key, __u32);
    __type(value, __u32);
    __uint(max_entries, 10240);
} active_fds SEC(".maps");

// ── Tracepoint handlers ───────────────────────────────────────────────────────

// trace_write fires on every write(fd, buf, count) call.
// It peeks at the first 128 bytes of buf to detect HTTP methods, then
// stores the method, path, and timestamp for the matching read exit.
SEC("tracepoint/syscalls/sys_enter_write")
int trace_write(struct trace_event_raw_sys_enter *ctx) {
    __u32 pid = bpf_get_current_pid_tgid() >> 32;
    int   fd  = (int)ctx->args[0];
    void *buf = (void *)ctx->args[1];
    __u64 len = ctx->args[2];

    if (len < 16) return 0;

    __u8 header[128] = {};
    bpf_probe_read_user(header, sizeof(header), buf);

    // Check for common HTTP methods by matching the first 4 bytes.
    int is_http = 0;
    if (header[0]=='G' && header[1]=='E' && header[2]=='T' && header[3]==' ') is_http=1;
    if (header[0]=='P' && header[1]=='O' && header[2]=='S' && header[3]=='T') is_http=1;
    if (header[0]=='P' && header[1]=='U' && header[2]=='T' && header[3]==' ') is_http=1;
    if (header[0]=='D' && header[1]=='E' && header[2]=='L' && header[3]=='E') is_http=1;
    if (header[0]=='P' && header[1]=='A' && header[2]=='T' && header[3]=='C') is_http=1;
    if (header[0]=='H' && header[1]=='E' && header[2]=='A' && header[3]=='D') is_http=1;

    if (!is_http) return 0;

    __u64 key = ((__u64)pid << 32) | (__u32)fd;
    __u64 now = bpf_ktime_get_ns();
    bpf_map_update_elem(&start_time, &key, &now, BPF_ANY);

    struct http_event event = {};
    event.pid          = pid;
    event.timestamp_ns = now;
    bpf_get_current_comm(event.comm, sizeof(event.comm));

    // Extract method: copy bytes until the first space.
    for (int i = 0; i < 7; i++) {
        if (header[i] == ' ') break;
        event.method[i] = header[i];
    }

    // Extract path: find the first space, then copy until the next space or '?'.
    // The '& 0x7f' mask keeps the index within [0,127] so the verifier is happy.
    __u8 path_start = 0;
    for (__u8 i = 0; i < 8; i++) {
        if (header[i] == ' ') { path_start = i + 1; break; }
    }
    for (int i = 0; i < 120; i++) {
        __u8 c = header[(path_start + i) & 0x7f];
        if (c == ' ' || c == '?' || c == 0) break;
        event.path[i] = c;
    }

    bpf_map_update_elem(&http_buf, &key, &event, BPF_ANY);
    return 0;
}

// trace_read_enter fires on every read(fd, buf, count) call.
// It saves the fd into active_fds so trace_read_exit can look it up.
SEC("tracepoint/syscalls/sys_enter_read")
int trace_read_enter(struct trace_event_raw_sys_enter *ctx) {
    __u32 pid = bpf_get_current_pid_tgid() >> 32;
    __u32 fd  = (int)ctx->args[0];
    bpf_map_update_elem(&active_fds, &pid, &fd, BPF_ANY);
    return 0;
}

// trace_read_exit fires when read() returns.
// It matches the return to a pending http_event, fills in the latency, and
// submits the completed event to the ring buffer.
SEC("tracepoint/syscalls/sys_exit_read")
int trace_read_exit(struct trace_event_raw_sys_exit *ctx) {
    __u32 pid = bpf_get_current_pid_tgid() >> 32;
    long  ret = ctx->ret;

    if (ret <= 0) return 0;

    __u32 *fdp = bpf_map_lookup_elem(&active_fds, &pid);
    if (!fdp) return 0;

    __u64 key = ((__u64)pid << 32) | *fdp;

    struct http_event *event = bpf_map_lookup_elem(&http_buf, &key);
    if (!event) return 0;

    __u64 now      = bpf_ktime_get_ns();
    __u64 *start   = bpf_map_lookup_elem(&start_time, &key);
    __u64 duration = start ? (now - *start) : 0;

    struct http_event *e = bpf_ringbuf_reserve(&http_events, sizeof(*e), 0);
    if (!e) return 0;

    *e             = *event;
    e->duration_ns = duration;
    bpf_ringbuf_submit(e, 0);

    bpf_map_delete_elem(&start_time, &key);
    bpf_map_delete_elem(&http_buf,   &key);
    bpf_map_delete_elem(&active_fds, &pid);
    return 0;
}

char LICENSE[] SEC("license") = "GPL";
